services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
    - "8000:8000"
    depends_on:
    - "catalogdb"
    environment:
    - ASPNETCORE_URLS=http://+:8000
    - DatabaseSettings__ConnectionString=mongodb://CatalogDb:27017
    - DatabaseSettings__DatabaseName=CatalogDb
    - DatabaseSettings__ProductsCollection=Products
    - DatabaseSettings__BrandsCollection=Brands
    - DatabaseSettings__TypesCollection=Types

  catalogdb:
     image: mongo
     container_name: catalogdb
     ports:
     - "27017:27017"
     volumes:
     - catalogdata:/data/db
  basketdb:
     image: redis:alpine
     container_name: basketdb
     ports:
     - "6379:6379"
     volumes:
     - basketdata:/data/db
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
     - "8001:8001"
    depends_on:
    - "basketdb"
    environment:
    - ASPNETCORE_URLS=http://+:8001
    - CacheSettings__ConnectionString=basketdb:6379

volumes:
  catalogdata:
  basketdata:
    
