services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
    - "8000:8000"
    depends_on:
    - "catalogdb"
    environment:
    - ASPNETCORE_URLS=http://+:8000
    - DatabaseSettings__ConnectionString=mongodb://CatalogDb:27017
    - DatabaseSettings__DatabaseName=CatalogDb
    - DatabaseSettings__ProductsCollection=Products
    - DatabaseSettings__BrandsCollection=Brands
    - DatabaseSettings__TypesCollection=Types

  catalogdb:
     image: mongo
     container_name: catalogdb
     ports:
     - "27017:27017"
     volumes:
     - catalogdata:/data/db
volumes:
  catalogdata:  
    