services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
    - "8000:8000"
    depends_on:
    - "catalogdb"
    environment:
    - ASPNETCORE_URLS=http://+:8000
    - DatabaseSettings__ConnectionString=mongodb://CatalogDb:27017
    - DatabaseSettings__DatabaseName=CatalogDb
    - DatabaseSettings__ProductsCollection=Products
    - DatabaseSettings__BrandsCollection=Brands
    - DatabaseSettings__TypesCollection=Types

  catalogdb:
     image: mongo
     container_name: catalogdb
     ports:
     - "27017:27017"
     volumes:
     - catalogdata:/data/db
  basketdb:
     image: redis:alpine
     container_name: basketdb
     ports:
     - "6379:6379"
     volumes:
     - basketdata:/data/db
  discountdb:
     image: postgres
     container_name: discountdb
     environment: 
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=Password@1
       - POSTGRES_DB=DiscountDb
     restart: always
     ports:
       - "5432:5432"
     volumes:
       - postgres_date:/var/lib/postgresql
     healthcheck:
        test: ["CMD-SHELL","pg_isready -U admin -d DiscountDb"]
        interval: 10s
        timeout: 5s
        retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ecommerce.com
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
 

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
     - "8001:8001"
    depends_on:
    - "basketdb"
    environment:
    - ASPNETCORE_URLS=http://+:8001
    - CacheSettings__ConnectionString=basketdb:6379
    - "GrpcSettings__DiscountUrl=http://discount.api:8080"
  portainer:
   image: portainer/portainer-ce
   container_name: portainer
   restart: always
   ports:
   - "8080:8000"
   - "9000:9000"
   volumes:
   - portainer_data:/data


  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "DatabaseSettings__Connection=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1"
    depends_on:
      discountdb:
        condition: service_healthy 
    ports:
     - "8002:8080"

volumes:
  catalogdata:
  basketdata:
  portainer_data:
  postgres_date:
  pgadmin_data:
